name: Restrict PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    name: Check Source Branch
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          if [[ "${{ github.head_ref }}" != "staging" ]]; then
            echo "Error: Pull requests to 'main' are only allowed from the 'pre-main' branch."
            exit 1
          fi
